services:
  mysql:
    image: mysql:latest
    container_name: sakila_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: sakila
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./sakila-data:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql # Este volumen es donde MySQL guarda los datos de la base de datos de manera persistente

